name: axe
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
jobs:
  axe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install --frozen-lockfile
      - run: npm run build --if-present
      - run: npm start & npx wait-on http://localhost:3000
      - name: Run axe
        run: |
          npm install -g @axe-core/cli
          axe http://localhost:3000, \
          http://localhost:3000/#profile, \
          http://localhost:3000/#groups, \
          http://localhost:3000/#billing, \
          http://localhost:3000/#clusters, \
          http://localhost:3000/#workspaces, \
          http://localhost:3000/#library/datasets, \
          http://localhost:3000/#library/showcase, \
          http://localhost:3000/#library/code, \
          http://localhost:3000/#workspaces/broad-dsde-alpha/large_submission, \
          http://localhost:3000/#workspaces/broad-dsde-alpha/large_submission/data, \
          http://localhost:3000/#workspaces/broad-dsde-alpha/large_submission/notebooks, \
          http://localhost:3000/#workspaces/broad-dsde-alpha/large_submission/workflows, \
          http://localhost:3000/#workspaces/broad-dsde-alpha/large_submission/job_history --exit --tags section508
